# Generated by Django 5.1.1 on 2024-10-03 06:45

import FPF.models
import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FPF', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DepartmentInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Designation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='student', max_length=50, unique=True)),
                ('full_name', models.CharField(default='Computer Science and Engineering', max_length=100)),
                ('type', models.CharField(choices=[('academic', 'Academic Designation'), ('administrative', 'Administrative Designation')], default='academic', max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='ExtraInfo',
            fields=[
                ('id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('title', models.CharField(choices=[('Mr.', 'Mr.'), ('Mrs.', 'Mrs.'), ('Ms.', 'Ms.'), ('Dr.', 'Dr.'), ('Professor', 'Prof.'), ('Shreemati', 'Shreemati'), ('Shree', 'Shree')], default='Dr.', max_length=20)),
                ('sex', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], default='M', max_length=2)),
                ('date_of_birth', models.DateField(default=datetime.date(1970, 1, 1))),
                ('user_status', models.CharField(choices=[('NEW', 'NEW'), ('PRESENT', 'PRESENT')], default='PRESENT', max_length=50)),
                ('address', models.TextField(default='', max_length=1000)),
                ('phone_no', models.BigIntegerField(default=9999999999, null=True)),
                ('user_type', models.CharField(choices=[('student', 'student'), ('staff', 'staff'), ('compounder', 'compounder'), ('faculty', 'faculty')], max_length=20)),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='globals/profile_pictures')),
                ('about_me', models.TextField(blank=True, default='NA', max_length=1000)),
                ('date_modified', models.DateTimeField(blank=True, null=True, verbose_name='date_updated')),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='FPF.departmentinfo')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ModuleAccess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('designation', models.CharField(max_length=155)),
                ('program_and_curriculum', models.BooleanField(default=False)),
                ('course_registration', models.BooleanField(default=False)),
                ('course_management', models.BooleanField(default=False)),
                ('other_academics', models.BooleanField(default=False)),
                ('spacs', models.BooleanField(default=False)),
                ('department', models.BooleanField(default=False)),
                ('examinations', models.BooleanField(default=False)),
                ('hr', models.BooleanField(default=False)),
                ('iwd', models.BooleanField(default=False)),
                ('complaint_management', models.BooleanField(default=False)),
                ('fts', models.BooleanField(default=False)),
                ('purchase_and_store', models.BooleanField(default=False)),
                ('rspc', models.BooleanField(default=False)),
                ('hostel_management', models.BooleanField(default=False)),
                ('mess_management', models.BooleanField(default=False)),
                ('gymkhana', models.BooleanField(default=False)),
                ('placement_cell', models.BooleanField(default=False)),
                ('visitor_hostel', models.BooleanField(default=False)),
                ('phc', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Faculty',
            fields=[
                ('id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='FPF.extrainfo')),
            ],
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='FPF.extrainfo')),
            ],
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)])),
                ('feedback', models.TextField(blank=True)),
                ('timestamp', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='fusion_feedback', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='IssueImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=FPF.models.Issue_image_directory)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Issue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_type', models.CharField(choices=[('feature_request', 'Feature Request'), ('bug_report', 'Bug Report'), ('security_issue', 'Security Issue'), ('ui_issue', 'User Interface Issue'), ('other', 'Other than the ones listed')], max_length=63)),
                ('module', models.CharField(choices=[('academic_information', 'Academic'), ('central_mess', 'Central Mess'), ('complaint_system', 'Complaint System'), ('eis', 'Employee Imformation System'), ('file_tracking', 'File Tracking System'), ('health_center', 'Health Center'), ('leave', 'Leave'), ('online_cms', 'Online Course Management System'), ('placement_cell', 'Placement Cell'), ('scholarships', 'Scholarships'), ('visitor_hostel', 'Visitor Hostel'), ('other', 'Other')], max_length=63)),
                ('closed', models.BooleanField(default=False)),
                ('text', models.TextField()),
                ('title', models.CharField(max_length=255)),
                ('timestamp', models.DateTimeField(auto_now=True)),
                ('added_on', models.DateTimeField(auto_now_add=True)),
                ('support', models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reported_issues', to=settings.AUTH_USER_MODEL)),
                ('images', models.ManyToManyField(blank=True, to='FPF.issueimage')),
            ],
        ),
        migrations.CreateModel(
            name='Project_Registration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_title', models.CharField(max_length=200)),
                ('sponsored_agency', models.CharField(max_length=100)),
                ('CO_PI', models.CharField(max_length=100, null=True)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('duration', models.IntegerField(default=0)),
                ('agreement', models.CharField(choices=[('Computer Graphics', 'Computer Graphics'), ('Machine Learning', 'Machine Learning'), ('Image Processing', 'Image Processing'), ('Data Structure', 'Data Structure')], default='NO', max_length=20)),
                ('amount_sanctioned', models.IntegerField(default=0)),
                ('project_type', models.CharField(choices=[('SRes', 'Sponsored Research'), ('Consultancy', 'Consultancy'), ('fig', 'Faculty Initiation Grant'), ('Testing', 'Testing')], max_length=25)),
                ('project_operated', models.CharField(choices=[('PI', 'Only by PI'), ('any', 'Either PI or CO-PI')], default='me', max_length=50)),
                ('remarks', models.CharField(max_length=200)),
                ('fund_recieved_date', models.DateField(blank=True, null=True)),
                ('HOD_response', models.CharField(choices=[('Forwarded', 'Forwarded'), ('Pending', 'Pending')], default='Pending', max_length=10)),
                ('DRSPC_response', models.CharField(choices=[('Approve', 'Approve'), ('Disapprove', 'Disapprove'), ('Pending', 'Pending')], default='Pending', max_length=10)),
                ('applied_date', models.DateField(blank=True, null=True)),
                ('description', models.CharField(max_length=200, null=True)),
                ('file', models.FileField(blank=True, null=True, upload_to='documents/')),
                ('PI_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='FPF.extrainfo')),
            ],
        ),
        migrations.CreateModel(
            name='Project_Reallocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(blank=True, null=True)),
                ('previous_budget_head', models.CharField(max_length=300)),
                ('previous_amount', models.IntegerField(default=0)),
                ('pf_no', models.CharField(max_length=100, null=True)),
                ('new_budget_head', models.CharField(max_length=300)),
                ('new_amount', models.IntegerField(default=0)),
                ('transfer_reason', models.CharField(max_length=300)),
                ('HOD_response', models.CharField(choices=[('Forwarded', 'Forwarded'), ('Pending', 'Pending')], default='Pending', max_length=10)),
                ('DRSPC_response', models.CharField(choices=[('Approve', 'Approve'), ('Disapprove', 'Disapprove'), ('Pending', 'Pending')], default='Pending', max_length=10)),
                ('project_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='FPF.project_registration')),
            ],
        ),
        migrations.CreateModel(
            name='Project_Extension',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(blank=True, null=True)),
                ('extended_duration', models.IntegerField(default=0)),
                ('extension_details', models.CharField(max_length=300)),
                ('HOD_response', models.CharField(choices=[('Forwarded', 'Forwarded'), ('Pending', 'Pending')], default='Pending', max_length=10)),
                ('DRSPC_response', models.CharField(choices=[('Approve', 'Approve'), ('Disapprove', 'Disapprove'), ('Pending', 'Pending')], default='Pending', max_length=10)),
                ('file', models.FileField(blank=True, null=True, upload_to='documents/')),
                ('project_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='FPF.project_registration')),
            ],
        ),
        migrations.CreateModel(
            name='Project_Closure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completion_date', models.DateField(blank=True, null=True)),
                ('date', models.DateField(blank=True, null=True)),
                ('expenses_dues', models.CharField(choices=[('Computer Graphics', 'Computer Graphics'), ('Machine Learning', 'Machine Learning'), ('Image Processing', 'Image Processing'), ('Data Structure', 'Data Structure')], default='Pending', max_length=20)),
                ('expenses_dues_description', models.CharField(blank=True, max_length=200, null=True)),
                ('payment_dues', models.CharField(choices=[('Computer Graphics', 'Computer Graphics'), ('Machine Learning', 'Machine Learning'), ('Image Processing', 'Image Processing'), ('Data Structure', 'Data Structure')], default='Pending', max_length=20)),
                ('payment_dues_description', models.CharField(blank=True, max_length=200, null=True)),
                ('salary_dues', models.CharField(choices=[('Computer Graphics', 'Computer Graphics'), ('Machine Learning', 'Machine Learning'), ('Image Processing', 'Image Processing'), ('Data Structure', 'Data Structure')], default='Pending', max_length=20)),
                ('salary_dues_description', models.CharField(blank=True, max_length=200, null=True)),
                ('advances_dues', models.CharField(choices=[('Computer Graphics', 'Computer Graphics'), ('Machine Learning', 'Machine Learning'), ('Image Processing', 'Image Processing'), ('Data Structure', 'Data Structure')], default='Pending', max_length=20)),
                ('advances_description', models.CharField(blank=True, max_length=200, null=True)),
                ('others_dues', models.CharField(choices=[('Computer Graphics', 'Computer Graphics'), ('Machine Learning', 'Machine Learning'), ('Image Processing', 'Image Processing'), ('Data Structure', 'Data Structure')], default='Pending', max_length=20)),
                ('other_dues_description', models.CharField(blank=True, max_length=200, null=True)),
                ('overhead_deducted', models.CharField(choices=[('Computer Graphics', 'Computer Graphics'), ('Machine Learning', 'Machine Learning'), ('Image Processing', 'Image Processing'), ('Data Structure', 'Data Structure')], default='Pending', max_length=20)),
                ('overhead_description', models.CharField(blank=True, max_length=200, null=True)),
                ('HOD_response', models.CharField(choices=[('Forwarded', 'Forwarded'), ('Pending', 'Pending')], default='Pending', max_length=10)),
                ('DRSPC_response', models.CharField(choices=[('Approve', 'Approve'), ('Disapprove', 'Disapprove'), ('Pending', 'Pending')], default='Pending', max_length=10)),
                ('remarks', models.CharField(max_length=300, null=True)),
                ('extended_duration', models.CharField(default='0', max_length=100, null=True)),
                ('project_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='FPF.project_registration')),
            ],
        ),
        migrations.CreateModel(
            name='HoldsDesignation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('held_at', models.DateTimeField(auto_now=True)),
                ('designation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='designees', to='FPF.designation')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='holds_designations', to=settings.AUTH_USER_MODEL)),
                ('working', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='current_designation', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'designation'), ('working', 'designation')},
            },
        ),
    ]
